### ISSUE TITLE
migration guides?

### ISSUE THREAD

**Issue by adam-moss** [BrianPugh/cyclopts#76] opened 2024-01-17 16:29 UTC
Howdy,

Saw the recent post on reddit about this and am checking it out.

Is there any plans to include some migration guides in the docs?  E.g. from Typer to cyclopts?

There are a couple of things that aren't obvious to me from reading so far, e.g. how to implement the equivalent of [nested subcommands](https://typer.tiangolo.com/tutorial/subcommands/nested-subcommands/).

Likewise is it possible to generate shell autocompletions and are there any patterns for incorporating telemetry?

Thanks!

**Comment by BrianPugh** [comment] 2024-01-17 18:22
I previously started writing a migration guide, but it ended up basically just being a duplicate of the [Getting Started](https://cyclopts.readthedocs.io/en/latest/getting_started.html) and the [Commands](https://cyclopts.readthedocs.io/en/latest/commands.html) sections of the documentation. The first example in the "Commands" documentation shows an example of registering a subapp (the syntax is the same as Typer).

Give the first few pages of the documentation a read through, and let me know if you have additional questions! I'm not against writing a migration guide, I just want to make sure it'd be done in a meaningful, non-redundant way.

**Comment by BrianPugh** [comment] 2024-01-21 22:18
So it's still pretty rough, but I added a migration page:

https://cyclopts.readthedocs.io/en/latest/migration/typer.html

I'll be closing this issue for now, but am still open to feedback/PRs about how this page can be improved!

**Closed by BrianPugh** 2024-01-21 22:18 UTC
Labels: documentation
